### ISSUE TITLE
Cannot load topic maps if Ontopia directory contains non-ascii characters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#317]
```
A user reports that all attempts to load topic maps fail with the following 
traceback:

INFO 2010-10-06 13:55:59,166 xml.XTMTopicMapReader - Parsing source 
file:/C:/Users/S%F8ren/Desktop/ontopia-5.1.0/apache-tomcat/webapps/omnigator/WEB
-INF/topicmaps/KevinsPlan.xtm
 INFO 2010-10-06 13:55:59,167 xml.XTMTopicMapReader - Parser: org.apache.crimson.parser.XMLReaderImpl@790192 (namespace support: true)
 ERROR 2010-10-06 13:55:59,176 [/omnigator].[jsp] - Servlet.service() for servlet jsp threw exception
 java.lang.IllegalArgumentException
	at sun.net.www.ParseUtil.decode(Unknown Source)
	at sun.net.www.protocol.file.Handler.openConnection(Unknown Source)
	at sun.net.www.protocol.file.Handler.openConnection(Unknown Source)
	at java.net.URL.openConnection(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at org.apache.crimson.parser.InputEntity.init(InputEntity.java:209)
	at org.apache.crimson.parser.Parser2.parseInternal(Parser2.java:471)
	at org.apache.crimson.parser.Parser2.parse(Parser2.java:305)
	at org.apache.crimson.parser.XMLReaderImpl.parse(XMLReaderImpl.java:442)
	at net.ontopia.topicmaps.xml.XTMTopicMapReader.read(XTMTopicMapReader.java:226)
	at net.ontopia.topicmaps.xml.XTMTopicMapReader.readAll(XTMTopicMapReader.java:272)
	at net.ontopia.topicmaps.xml.XTMTopicMapReader.importInto(XTMTopicMapReader.java:291)
	at net.ontopia.topicmaps.entry.AbstractOntopolyURLReference.loadTopicMap(AbstractOntopolyURLReference.java:72)
	at net.ontopia.topicmaps.entry.AbstractURLTopicMapReference.open(AbstractURLTopicMapReference.java:133)
	at net.ontopia.topicmaps.entry.AbstractURLTopicMapReference.createStore(AbstractURLTopicMapReference.java:184)
	at net.ontopia.topicmaps.entry.TopicMaps.createStore(TopicMaps.java:50)
	at net.ontopia.topicmaps.entry.TopicMaps.createStore(TopicMaps.java:34)
	at net.ontopia.topicmaps.nav2.impl.basic.NavigatorApplication.getTopicMapById(NavigatorApplication.java:192)
	at net.ontopia.topicmaps.nav2.impl.basic.NavigatorApplication.getTopicMapById(NavigatorApplication.java:181)
	at net.ontopia.topicmaps.nav2.taglibs.logic.ContextTag.doStartTag(ContextTag.java:147)
	at org.apache.jsp.models.topicmap_005fcomplete_jsp._jspService(topicmap_005fcomplete_jsp.java:132)

The underlying cause appears to be this Java bug:
  http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6522294

However, we should correctly percent-encode the "ø" character to avoid this 
issue in the first place.
```

Original issue reported on code.google.com by `lar...@gmail.com` on 18 Oct 2010 at 9:30

**Comment by qsiebers** [comment]
Verified that they are different issues. This issue was fixed in java 7u10, and now that Ontopia is officially on java 7, we can consider this fixed. 

Verified that it works now (item identifier of a topic as seen in omnigator):
`file:/Users/[...]/dist-%C3%B8-t%C3%B6p%C3%BCc-m%C3%A4p/topicmaps/ADL-FTT.xtm#id126`

Note that unicode characters within the filename of the topicmap are still causing errors due to #206.
