### ISSUE TITLE
NPE in DB2TM for topic maps without base locator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#348]
```
Given an RDBMS topic map with no base locator and a DB2TM mapping like

  <relation name="IFSAPP.EQUIPMENT_OBJECT"
            columns="contract mch_code mch_name company sup_mch_code">
    <topic id="superior">
      <item-identifier>#eq${sup_mch_code}</item-identifier>
    </topic>

the result is this traceback

java.lang.NullPointerException
    at net.ontopia.topicmaps.db2tm.Utils.getTopic(Utils.java:111)
    at net.ontopia.topicmaps.db2tm.Context.loadExtents(Context.java:335)
    at net.ontopia.topicmaps.db2tm.Processor.synchronizeRelations(Processor.java:1492)
    at net.ontopia.topicmaps.db2tm.Processor.synchronizeRelations(Processor.java:1360)
    at net.ontopia.topicmaps.db2tm.DB2TM.sync(DB2TM.java:65)
    at org.apache.jsp.plugins.db2tm.run_jsp._jspService(run_jsp.java:67)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:98)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:331)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:329)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:265)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:172)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:875)
    at 
```

Original issue reported on code.google.com by `lar...@gmail.com` on 26 Jan 2011 at 1:10

**Comment by qsiebers** [comment]
Added testcase in 81132c23491955d2add5c74ff9df42c5c7669148

**Comment by qsiebers** [comment]
Fixed by 5fd39166f8d7ca404e19a89d56d6335d22603632

**Comment by qsiebers** [comment]
Linking original reporter: @larsga

**Comment by larsga** [comment]
👍 

Nice to see there's a concise test case, too.
