### ISSUE TITLE
Omnigator fulltext indexes not working

### ISSUE THREAD

**Issue by Wolfhart** [ontopia/ontopia#522]
Hello,

I hope that this is the right place to ask for help with a problem with Ontopia that I am facing. The Google group <ontopia@googlegroups.com> that I used two years ago to report a problem does not seem to exist anymore.

I recently reinstalled my computer and am now unable to get the Omnigator working again. I am hoping that one of you can help.

The current version (5.3.0) does not work fully on my system (Ubuntu 13.10) because of the problem that I reported in 2013, namely that, when I search the indexed topic map for a word, I get the error message "directory '/null/[name of topic map].ltm' does not exist". The thread from 2013 is to be found here: https://groups.google.com/forum/#!topic/ontopia/TsWEo7ft6t8 (I am sorry that I didn't respond to the last message in this thread. By the time I received that last message, I had found a workaround, and so I forgot to respond.)

The way I worked around the problem in 2013 was to install an older version of Omnigator, 5.0.2, which worked fine on my system. I tried to use this solution again now, but I am facing the problem that I cannot find the release of version 5.0.2 that I am used to. I can see the release of version 5.0.2 on this website (https://github.com/ontopia/ontopia/releases/tag/release-5.0.2), but this version is different from the one I know. I cannot find in this release the startup.sh script that I used to use for launching the Omnigator.

So my question is this: How do I launch the Omnigator in the release-5.0.2 version that I find here on GitHub, or, alternatively, where do I find the variant of version 5.0.2 with the startup.sh script that I used to have? Or, other alternative, how can I solve the problem of "directory '/null/[name of topic map].ltm' does not exist" in the current version?

Thank you in advance for your help!
Wolfhart

**Comment by qsiebers** [comment]
Dear Wolfhart, 

I think I'm able to reproduce this issue. Is this the message you are getting:

```
Stack Trace of root cause is:
org.apache.lucene.store.NoSuchDirectoryException: directory '/apps/ontopia/5.3.0/apache-tomcat/null/pokemon.ltm' does not exist
	at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:516)
	at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:543)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:564)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:73)
	at org.apache.lucene.index.IndexReader.open(IndexReader.java:476)
	at org.apache.lucene.index.IndexReader.open(IndexReader.java:300)
	at org.apache.lucene.search.IndexSearcher.(IndexSearcher.java:87)
	at net.ontopia.infoset.fulltext.impl.lucene.LuceneSearcher.(LuceneSearcher.java:109)
	at net.ontopia.infoset.fulltext.impl.lucene.LuceneSearcher.(LuceneSearcher.java:81)
	at net.ontopia.infoset.fulltext.impl.lucene.LuceneSearcher.(LuceneSearcher.java:68)
	at org.apache.jsp.plugins.fulltext.search_jsp._jspService(search_jsp.java:309)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Wolfhart** [comment]
Dear Quintin,

Thank you for the reply! Yes, the log in apache-tomcat/logs that I find 
looks very similar to yours. Here it is:

Dec 10, 2015 12:04:13 AM org.apache.catalina.core.StandardWrapperValve 
invoke
SEVERE: Servlet.service() for servlet jsp threw exception
org.apache.lucene.store.NoSuchDirectoryException: directory 
'/null/zettelkasten.ltm' does not exist
     at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:516)
     at org.apache.lucene.store.FSDirectory.listAll(FSDirectory.java:543)
     at 
org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:564)
     at 
org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:73)
     at org.apache.lucene.index.IndexReader.open(IndexReader.java:476)
     at org.apache.lucene.index.IndexReader.open(IndexReader.java:300)
     at org.apache.lucene.search.IndexSearcher.<init>(IndexSearcher.java:87)
     at 
net.ontopia.infoset.fulltext.impl.lucene.LuceneSearcher.<init>(LuceneSearcher.java:109)
     at 
net.ontopia.infoset.fulltext.impl.lucene.LuceneSearcher.<init>(LuceneSearcher.java:81)
     at 
net.ontopia.infoset.fulltext.impl.lucene.LuceneSearcher.<init>(LuceneSearcher.java:68)
     at 
org.apache.jsp.plugins.fulltext.search_jsp._jspService(search_jsp.java:309)
     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
     at 
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:388)
     at 
org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
     at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
     at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
     at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
     at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
     at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
     at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
     at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
     at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
     at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
     at 
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
     at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
     at 
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
     at java.lang.Thread.run(Thread.java:724)

**Comment by qsiebers** [comment]
I've found the reason(s) for this. It seems #161 was only partially fixed. After I fix #161 I'll send you a fix that you can apply to your local installation until a new Ontopia is released

**Comment by qsiebers** [comment]
To fix this in your local Ontopia:

Replace the content of the ```{ontopia}/apache-tomcat/webapps/omnigator/plugins/fulltext/search.jsp``` file with the content here: https://raw.githubusercontent.com/ontopia/ontopia/305b2a253cc29a0fbcc422772ce230200e0fcf26/webapp-omnigator/src/main/webapp/plugins/fulltext/search.jsp

Or, apply the whole commit if you are comfortable using a patch: https://github.com/ontopia/ontopia/commit/305b2a253cc29a0fbcc422772ce230200e0fcf26.patch

**Comment by Wolfhart** [comment]
Dear Quintin,

The patch resolved the issue. Thank you very much!

Best,
Wolfhart
